// Generated by the Freon Language Generator.
import { FreNamedNode, FreStdlib } from "@freon4dsl/core";

export class CustomMuDForM_ModelStdlib implements FreStdlib {
    // add all your extra predefined instances here
    get elements(): FreNamedNode[] {
        return [];
    }
}
