// Generated by the Freon Language Generator.
import { FreProjection, FreCombinedActions, FreTyper, FreStdlib, FreScoper } from "@freon4dsl/core";
import { CustomMuDForM_ModelActions, CustomMuDForM_ModelProjection } from "../editor/index.js";
import { CustomMuDForM_ModelScoper } from "../scoper/index.js";
import { CustomMuDForM_ModelTyperPart } from "../typer/CustomMuDForM_ModelTyperPart.js";
import { CustomMuDForM_ModelValidator } from "../validator/index.js";
import { CustomMuDForM_ModelStdlib } from "../stdlib/CustomMuDForM_ModelStdlib.js";
import { MuDForM_ModelCheckerInterface } from "../validator/gen/index.js";

/**
 * Class FreonConfiguration is the place where you can add all your customisations.
 * These will be used through the 'freonConfiguration' constant by any generated
 * part of your language environment.
 */
class FreonConfiguration {
    // add your custom editor projections here
    customProjection: FreProjection[] = [new CustomMuDForM_ModelProjection()];
    // add your custom editor actions here
    customActions: FreCombinedActions[] = [new CustomMuDForM_ModelActions()];
    // add your custom validations here
    customValidations: MuDForM_ModelCheckerInterface[] = [new CustomMuDForM_ModelValidator()];
    // add your custom scopers here
    customScopers: FreScoper[] = [new CustomMuDForM_ModelScoper()];
    // add your custom type-providers here
    customTypers: FreTyper[] = [new CustomMuDForM_ModelTyperPart()];
    // add extra predefined instances here
    customStdLibs: FreStdlib[] = [new CustomMuDForM_ModelStdlib()];
}

export const freonConfiguration = new FreonConfiguration();
