// Generated by the Freon Language Generator.
// Generated once, will NEVER be overwritten.
import { InterpreterContext, IMainInterpreter, RtObject } from "@freon4dsl/core";
import { StarterModelInterpreterBase } from "./gen/StarterModelInterpreterBase.js";

let main: IMainInterpreter;

/**
 * The class containing all interpreter functions written by the language engineer.
 * This class is initially empty, and will not be overwritten if it already exists.
 */
export class StarterModelInterpreter extends StarterModelInterpreterBase {
    constructor(m: IMainInterpreter) {
        super();
        main = m;
    }
}
